const PostActiontype = {
  POST_SUNDAY_MESSAGE_START: 'POST_SUNDAY_MESSAGE_START',
  POST_SUNDAY_MESSAGE_SUCCESS: 'POST_SUNDAY_MESSAGE_SUCCESS',
  POST_SUNDAY_MESSAGE_FAILED: 'POST_SUNDAY_MESSAGE_FAILED',
};

export default PostActiontype;