const PostActiontype = {
  POST_SUNDAY_MESSAGE_START: 'POST_SUNDAY_MESSAGE_START',
  POST_SUNDAY_MESSAGE_SUCCESS: 'POST_SUNDAY_MESSAGE_SUCCESS',
  POST_SUNDAY_MESSAGE_FAILED: 'POST_SUNDAY_MESSAGE_FAILED',

  POST_BIBLE_MESSAGE_START: 'POST_BIBLE_MESSAGE_START',
  POST_BIBLE_MESSAGE_SUCCESS: 'POST_BIBLE_MESSAGE_SUCCESS',
  POST_BIBLE_MESSAGE_FAILED: 'POST_BIBLE_MESSAGE_FAILED',

  POST_BIBLE_MESSAGE_COMMENTS_START: 'POST_BIBLE_MESSAGE_COMMENTS_START',
  POST_BIBLE_MESSAGE_COMMENTS_SUCCESS: 'POST_BIBLE_MESSAGE_COMMENTS_SUCCESS',
  POST_BIBLE_MESSAGE_COMMENTS_FAILED: 'POST_BIBLE_MESSAGE_COMMENTS_FAILED',
};

export default PostActiontype;